### ISSUE TITLE
v1 breaks material-ui-pickers

### ISSUE THREAD

**Issue by barbalex** [dmtrKovalenko/date-io#15]
When updating from v0.0.2 to 1.0.0 a once working app now errors:

```
material-ui-pickers.esm.js:1386 Uncaught TypeError: _this.props.utils.getStartOfMonth is not a function
    at new Calendar (material-ui-pickers.esm.js:1386)
    at constructClassInstance (react-dom.development.js:13082)
    at updateClassComponent (react-dom.development.js:14978)
    at beginWork (react-dom.development.js:15845)
    at performUnitOfWork (react-dom.development.js:18879)
    at workLoop (react-dom.development.js:18920)
    at HTMLUnknownElement.callCallback (react-dom.development.js:147)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:196)
    at invokeGuardedCallback (react-dom.development.js:250)
    at replayUnitOfWork (react-dom.development.js:18127)
    at renderRoot (react-dom.development.js:19038)
    at performWorkOnRoot (react-dom.development.js:19941)
    at performWork (react-dom.development.js:19851)
    at performSyncWork (react-dom.development.js:19825)
    at interactiveUpdates$1 (react-dom.development.js:20113)
    at interactiveUpdates (react-dom.development.js:2267)
    at dispatchInteractiveEvent (react-dom.development.js:5081)
```

**Comment by barbalex** [comment]
Before updating I tried to find out what has changed i v1 as it suggests breaking changes. But I could not find any information.

**Comment by dmtrKovalenko** [comment]
Yes, I know. We should update but there is a problem that I am solving right now. Sorry for inconvenience

**Comment by dmtrKovalenko** [comment]
Fixed now

**Comment by dmtrKovalenko** [comment]
Update to v1.0.1

**Comment by barbalex** [comment]
works nicely, thanks
