### ISSUE TITLE
Missing methods @date-io/date-fns@2.10.0

### ISSUE THREAD

**Issue by wingsbob** [dmtrKovalenko/date-io#464]
@date-io/date-fns@2.10.0 is missing the following methods in the compiled code:
addSeconds, addMinutes, addHours, addWeeks

If you open up the `node_modules` folder where `@date-io/date-fns@2.10.0` is installed, in the `src` folder you'll be able to see `date-fns-utils.ts` with implementations of the above methods. However, the `.d.ts` and `.js` files in the `build` folder do not have these, which causes TS compilation errors when using `@material-ui/pickers` 😭

Happy to provide any additional information if necessary 😄

**Comment by dmtrKovalenko** [comment]
I hate lerna. 

We need a new tool for mono repo management. Will publish the fix in 20 minutes

**Comment by dmtrKovalenko** [comment]
Please verify it works with 2.10.6

**Comment by wingsbob** [comment]
Works like a charm, thanks! 👍
